// This file is auto-generated by the build script
// Do not modify manually - it will be overwritten during build

export const version = '3.1.4-wasm'; // Default value, replaced during build
export const name = 'steamapi';

/**
 * Environment detection utilities for WASM compatibility
 */

/**
 * Check if we're running in a WASM environment
 */
export function isWasmEnvironment(): boolean {
  return typeof WebAssembly !== 'undefined' && 
         typeof WebAssembly.Module === 'function';
}

/**
 * Check if we're running in a browser environment
 */
export function isBrowserEnvironment(): boolean {
  return typeof window !== 'undefined' && 
         typeof document !== 'undefined';
}

/**
 * Check if we're running in a Web Worker environment
 */
export function isWebWorkerEnvironment(): boolean {
  return typeof self !== 'undefined' && 
         typeof importScripts === 'function';
}

/**
 * Check if Date API is available and working
 */
export function isDateApiAvailable(): boolean {
  try {
    return typeof Date !== 'undefined' && 
           typeof Date.now === 'function' &&
           !isNaN(Date.now());
  } catch {
    return false;
  }
}

/**
 * Safe Date.now() implementation with fallback
 */
export function safeDateNow(): number {
  if (isDateApiAvailable()) {
    return Date.now();
  }
  
  // Fallback for environments without Date API
  // Return a fixed timestamp that won't break cache logic
  return 1640995200000; // 2022-01-01 00:00:00 UTC
} 